spring.application.name=ai-client
server.port=8080
server.error.include-stacktrace=never

spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0
spring.ai.google.genai.chat.options.max-output-tokens=2048
spring.ai.google.genai.chat.options.thinking-budget=0
spring.ai.google.genai.chat.options.include-thoughts=false

spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.streamable-http.connections.product-db.url=http://localhost:8081
